

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/companyproj?rewriteBatchedStatements=true" #
    username: yipingx
    password: Xyp54250
#    username: "matt.xia"
#    password: "matt.xia.1234"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update #create update
    properties:
      hibernate:
        format_sql: false
        jdbc.batch_size: 10
        order_inserts: true
        order_updates: true
        generate_statistics: true
  application:
    name: JwtApp



logging:
  config: config/resources/log4j2.xml