all-configs:
  server-port:
    demo-caller: 8080
    demo-echo: 8081
    demo-caller-log4j2: 8082
    config-secret: 8083
  app-name:
    demo-caller: demo-caller
    demo-echo: demo-echo
    demo-caller-log4j2: demo-caller-log4j2
    config-secret: config-secret
  server-ssl:
    demo-echo:
      enabled: false
      bundle: defaultBundle
      client-auth: none

spring:
  profiles:
    default: dev
  ssl:
    bundle:
      jks:
        defaultBundle:
          keystore:
            location: "classpath:keystore/keystore.p12"
            password: "123456"
          truststore:
            location: "classpath:keystore/certstore.p12"
            password: "123456"

