
vault:
#  url: "https://localhost:8180"
  url: "https://vault.tcghl.com"
#  ca-path: "d:/tools/vault/1.14/ca.pem"
  ca-path: "d:/tools/vault/1.14/tcghl-com-crt.pem"
  entries:
    -
#      secret-path: "/v1/kv_xyp/data/dev"
      secret-path: "/v1/secret/data/dev/paradise/keystore"
      keys:
#        -
#          field: "npassword"
#          value: "nacos_password"
        -
          field: "password"
          value: "other_password"