
vault:
  url: "https://localhost:8180"
  ca-path: "d:/tools/vault/1.14/ca.pem"
  entries:
    secret-path: "/v1/kv_xyp/data/dev"
    keys:
      -
        field: "npassword"
        value: "nacos_password"
      -
        field: "password"
        value: "other_password"