server:
  port: ${all-configs.server-port.demo-caller}
  ssl:
    enabled: false

spring:
  application:
    name: ${all-configs.app-name.demo-caller}

# add tag in metrics so that we can use in prometheus
management:
  metrics:
    tags:
      app-name: ${spring.application.name}
