apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
  - name: Zipkin
    type: zipkin
    url: http://zipkin:9411
    access: proxy
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    readOnly: true