variables:
  mvn_opts: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
  paths:
    - $CI_PROJECT_DIR/.m2/repository/

stages:
  - preMergeCheck
  - test
  - mergeTest
  - qodana
  - deploy
  - finish

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH

qodana:
  only:
    - main
    - dev
    - home
    - merge_requests
  image:
    name: jetbrains/qodana-jvm
    entrypoint: [""]
  variables:
    QODANA_TOKEN: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJvcmdhbml6YXRpb24iOiJwbm9rOSIsInByb2plY3QiOiIzeVBhTSIsInRva2VuIjoiQUdxWXIifQ.FEZ0QDLnKyzKf-ox6ptGwDKeJLl-jWoX2qfbpDwYZms"
  script:
    #- qodana --save-report --results-dir=$CI_PROJECT_DIR/.qodana
    - pwd
    - echo "fake"
    - printenv


job-preMergeCheck:
  stage: preMergeCheck
  image: maven:3.8.3-openjdk-17
  only:
    - merge_requests
  script:
    - echo "pass jira number check  ";

# merge should test
job-test:
  stage: test
  tags:
    - maven3.8-java17-yipingx
#  image: maven:3.8.3-openjdk-17
  script:
    - echo "Hello, this is test."
    - pwd
    - cat /home/gitlab-runner/cache/aaa.txt
    - echo "aaaa" >> /home/gitlab-runner/cache/bbb.txt
    - cat ./pom.xml
    - cat ./caller/pom.xml
    - cat ./echo/pom.xml
    - mvn compile test -Dspring.profiles.active=test $mvn_opts
    - ls -l ./.m2/repository

# merge should test
job-mergeTest:
  stage: mergeTest
  #  tags:
  #    - maven3.8-java17
  image: maven:3.8.3-openjdk-17
  only:
    - merge_requests
  script:
    - echo "Hello, this is test."
#    - mvn compile test -Dspring.profiles.active=test

# approve merge should deploy
job-deploy:
  stage: deploy
  tags:
    - maven3.8-java17-yipingx
#  tags:
#    - maven3.8-java17
  #  image: maven:3.8.3-openjdk-17
  script:
    - echo "Hello, this is deploy. 1 $CI_MERGE_REQUEST_TARGET_BRANCH_SHA"
    - echo "Hello, this is deploy. 1 $CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
    - pwd
    - printenv
    - cat ./pom.xml
    - cat ./caller/pom.xml
    - cat ./echo/pom.xml
    - npx semantic-release
    - cat ./pom.xml
    - cat ./caller/pom.xml
    - cat ./echo/pom.xml

job-finish:
  stage: finish
#  tags:
#    - maven3.8-java17
  #  image: maven:3.8.3-openjdk-17
  script:
    - echo "Hello, this is finish. add sth  22"
    - printenv