plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/exec"
    - verifyReleaseCmd: 'mvn versions:set -DnewVersion="${nextRelease.version}" -DprocessAllModules=true && echo "NEXT_VERSION=${nextRelease.version}" >> build.env'
  - "@semantic-release/gitlab"
  - -  "@semantic-release/git"
    - assets:
        - pom.xml
        - caller/pom.xml
        - echo/pom.xml
      message: "chore(release): bump ${nextRelease.version}"

branches:
  - "master"
  - "home"
  - "office"
  - "dev"
  - "pre-master"
  - "+([0-9])?(.{+([0-9]),x}).x"