concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "mvn3.8java17"
  url = "https://gitlab.com"
  id = 25225751
  token = "glrt-96YMWDTMSZYjjugfwTbU"
  token_obtained_at = 2023-07-16T06:34:35Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "maven:3.8.3-openjdk-17"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0

[[runners]]
  name = "maven3.8-java17"
  url = "https://gitlab.com"
  id = 25229562
  token = "glrt-zka1wXDbyt4hq-pwxFfb"
  token_obtained_at = 2023-07-16T12:18:12Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
  [runners.docker]
    tls_verify = false
    image = "maven:3.8.3-openjdk-17"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
