server:
  port: 8080

spring:
  application:
    name: oauth2-client
  security:
    oauth2:
      client:
        registration:
          github:
            ## setup in github
            clientId: cc30276322adbf59445b
            clientSecret: f98fc5deb9ecd3af6da5e376264dcaea8b73adde
          yipingx:
            provider: "yipingx"
            clientId: "oidc-client"
            clientSecret: "secret"
            authorization-grant-type: "authorization_code"
            client-authentication-method: "client_secret_basic"
            redirect-uri: "http://localhost:8080/login/oauth2/code/yipingx"
            scope:
              - "openid"
              - "user.read"
        provider:
          yipingx:
            issuer-uri: "http://127.0.0.1:8081"
