spring:
  security:
    oauth2:
      client:
        registration:
          yipingx:
            provider: "yipingx"
            clientId: "oidc-client"
            clientSecret: "secret"
            authorization-grant-type: "authorization_code"
            client-authentication-method: "client_secret_basic"
            redirect-uri: "http://${local_host}:8080/login/oauth2/code/yipingx"
            scope:
              - "openid"
              - "user.read"
        provider:
          yipingx:
            issuer-uri: "http://${v_host}:8081"
  cloud:
    discovery:
      client:
        simple:
          instances:
            kyc:
              - uri: http://1.2.3.4:8100
                instance-id: kyc
                service-id: kyc
              - uri: http://2.1.3.4:8100
                instance-id: kyc
                service-id: kyc
    gateway:
      routes:
        - id: kyc
          uri: lb://kyc
          filters:
            - TokenRelay=
          predicates:
            - Path=/kyc/api/**
        - id: mycoreinfo-participant
          uri: http://3.2.1.4:7002
          filters:
            - TokenRelay=
          predicates:
            - Path=/mycoreinfo-participant/graphql