spring.datasource:
  url: jdbc:mysql://localhost:3306/dummyUserApp
  username: root
  password: Xyp54250


## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa:
  properties.hibernate:
    dialect: org.hibernate.dialect.MySQLDialect
    format_sql: true
  hibernate.ddl-auto: create
  show-sql: true

#logging.level.org.hibernate.SQL: debug
#logging.level.org.hibernate.type.descriptor.sql: trace
# Hibernate ddl auto (create, create-drop, validate, update)



# enable/disable https
server.ssl.enabled: true
# keystore format
server.ssl.key-store-type: PKCS12
# keystore location
server.ssl.key-store: "classpath:keystore/keystore.p12"
# keystore password
server.ssl.key-store-password: p@ssw0rd
server.ssl.client-auth: "need"

# SSL protocol to use
server.ssl.protocol: TLS
# Enabled SSL protocols
server.ssl.enabled-protocols: TLSv1.2
# https://www.baeldung.com/spring-tls-setup
# keytool -genkeypair -alias baeldung -keyalg RSA -keysize 4096  -validity 90 -dname "CN=localhost" -keypass p@ssw0rd -keystore keystore.p12  -storeType PKCS12 -storepass p@ssw0rd