server:
  port: 8083
  tomcat:
    resource:
      allow-caching: false

spring:
  application:
    name: web-api-jwt
  cloud:
    vault:
      enabled: false
  config:
    additional-location: classpath:add.properties

management:
  health:
    influxdb:
      enabled: false
  influx:
    metrics:
      export:
        enabled: false

logging:
  config: classpath:log4j2-spring.xml
