server:
  port: 8082
  servlet:
    context-path: /api

spring:
  application:
    name: web-api

  datasource:
    driver-class-name: ${db_driver}
    url: ${db_url}
    username: ${db_user}
    password: ${db_token}
    hikari:
      connection-test-query: "select 1 "
      maximum-pool-size: 3
  jpa:
    hibernate:
      ddl-auto: none
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_batch_fetch_size: 10
        jdbc:
          batch_size: 100
          lob:
            non_contextual_creation: true
        format_sql: false
        use_sql_comments: true
        generate_statistics: false
        default_schema: test
        order_updates: true
        order_inserts: true

    open-in-view: false
    show-sql: true
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: ${oauth2_introspection_uri}
          client-id: ${oauth2_client_id}
          client-secret: ${oauth2_client_secret}
#        jwt:
#          issuer-uri: "http://${v_host}:8081"
#          issuer-uri: https://token.actions.githubusercontent.com
#          jwk-set-uri: https://token.actions.githubusercontent.com/.well-known/jwks

management:
  health:
    influxdb:
      enabled: false
  influx:
    metrics:
      export:
        enabled: false
  metrics:
    tags:
      app-name: ${spring.application.name}
      hostname: ${hostname:-}
mybatis:
  mapper-locations: classpath:/mybatis/*.xml

org:
  xyp:
    shared:
      id-gen:
        schema: test
        table: id_table
        entity-name-column: entity_name
        prev-value-column: prev_value
        step-size-column: step_size
        fetch-size-column: fetch_size

logging:
  config: classpath:log4j2-spring.xml

springdoc:
  swagger-ui:
    enabled: true
    path: swagger-ui.html


