server:
  port: 8082

spring:
  application:
    name: web
  datasource:
    driver-class-name: ${qa_db_driver}
    url: ${qa_db_url}
    username: ${qa_db_user}
    password: ${qa_db_token}
    hikari:
      maximum-pool-size: 3
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
        jdbc:
          batch_size: 100
          lob:
            non_contextual_creation: true
        format_sql: true
        use_sql_comments: false
        generate_statistics: true
        dialect: org.hibernate.dialect.SQLServerDialect
    open-in-view: false
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://${v_host}:8081"
#          issuer-uri: https://token.actions.githubusercontent.com
#          jwk-set-uri: https://token.actions.githubusercontent.com/.well-known/jwks
        opaquetoken:
          client-id: "client-id"
          client-secret: "secret"
          introspection-uri: "url"

logging:
  config: classpath:log4j2-spring.xml
