receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:5555

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  attributes:
    actions:
      - action: insert
        key: loki.attribute.labels
        value: event.domain, event.name
  resource:
    attributes:
      - action: insert
        key: loki.resource.labels
        value: service.name, service.namespace
      - action: insert
        key: loki.format
        value: logfmt

exporters:
  prometheus:
    endpoint: collector:6666
    namespace: xyp
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
  logging:
    loglevel: info

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      #      processors: [batch]
      exporters: [otlp]

  telemetry:
    logs:
      level: info
