receivers:
  otlp:  # for tracing
    protocols:
      grpc:
        endpoint: 0.0.0.0:5555
#      http:
  otlp/2:  # for logging
    protocols:
      grpc:
        endpoint: 0.0.0.0:5556

processors:
  batch:
    timeout: 3s
    send_batch_size: 1024
  attributes:
    actions:
      - action: insert
        key: loki.attribute.labels
        value: event.domain, event.name
  resource:
    attributes:
      - action: insert
        key: loki.resource.labels
        value: service.name, service.namespace
      - action: insert
        key: loki.format
        value: logfmt

exporters:
  prometheus:
    endpoint: collector:6666
    namespace: xyp
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
  logging:
    verbosity: detailed
  ## only contrib version of otel collector contains loki exporter
  ## see docker config
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    default_labels_enabled:
      exporter: false
      job: true

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    logs:
      receivers: [otlp/2]
      processors: [batch]
      exporters: [loki]
  telemetry:
    logs:
      level: debug
