
server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: "cc30276322adbf59445b"
            client-secret: "b79bc4c23ffc3c6c6699708b50d4991eb19d9fd1"

logging:
  config: "config/resources/log4j2.xml"
#  level:
#    root: info
#    org:
#      springframework: debug
