server.port: 8093
#docker run -d -p 9411:9411 openzipkin/zipkin

management:
  tracing.sampling.probability: 1.0
  endpoints.web.exposure.include: prometheus

spring.ssl.bundle:
  jks:
    clientStoreJks:
      keystore:
        location: "classpath:keystore/keystore.p12"
        password: "123456"
      truststore:
        location: "classpath:keystore/certstore.p12"
        password: "123456"
# No need to provide a trust store if server doesn't accept client ssl authentication.
# But need trust store if ssl call to another server

server:
  ssl:
    enabled: false
    bundle: "clientStoreJks"


spring.datasource:
  url: jdbc:mysql://localhost:3306/companyproj?rewriteBatchedStatements=true #
  #  username: matt.xia
  #  password: Q1w2e3r4
  username: yipingx
  password: Xyp54250
  driver-class-name: com.mysql.cj.jdbc.Driver

logging.config: classpath:log4j2.xml

app:
  service-principal: 111
  keytab-location: 111

springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    path: "swagger-ui-custom.html"

echo:
  url: "http://localhost:8094/echo"


spring:
  cloud:
    nacos:
      discovery:
        server-addr: "172.19.83.237:8848"
#    openfeign:
#      client:
#        config:
#          echoServer:
#            url: "https://echoServer"
  application:
    name: callerServer

# if not provide below, still work:
#spring.cloud.loadbalancer.nacos.enabled: true

