version: '3'

services:

  demo-otel:
    image: demo-otel:latest
#    build:
#      context: ..
#      dockerfile: docker/demo-otel.Dockerfile
    volumes:
      - ../:/app
      - c:\Users\matt.xia\.m2:/mvn/
      - c:\Users\matt.xia\.m2\repository:/mvn/repository
    extra_hosts: ['host.docker.internal:host-gateway']
    environment:
      - JAVA_TOOL_OPTIONS='-javaagent:/app/opentelemetry-javaagent.jar'
      - OTEL_TRACES_EXPORTER=logging
      - OTEL_METRICS_EXPORTER=logging
      - OTEL_LOGS_EXPORTER=logging
    command: "mvn compile spring-boot:run -pl :demo-otel -Dmaven.repo.local=/mvn/repository"
    ports:
      - 8080:8080

  demo-caller:
    image: demo-otel:latest
    #    build:
    #      context: ..
    #      dockerfile: docker/demo-otel.Dockerfile
    volumes:
      - ../:/app
      - c:\Users\matt.xia\.m2:/mvn/
      - c:\Users\matt.xia\.m2\repository:/mvn/repository
    extra_hosts: ['host.docker.internal:host-gateway']
    environment:
      - JAVA_TOOL_OPTIONS='-javaagent:/app/opentelemetry-javaagent.jar'
      - OTEL_TRACES_EXPORTER=logging
      - OTEL_METRICS_EXPORTER=logging
      - OTEL_LOGS_EXPORTER=logging
    command: "mvn compile spring-boot:run -pl :demo-caller -Dmaven.repo.local=/mvn/repository"
    ports:
      - 8093:8093

#  collector:
#    image: logzio/otel-collector-traces
#    environment:
#      - LOGZIO_REGION=${LOGZIO_REGION}
#      - LOGZIO_TRACES_TOKEN=${LOGZIO_TRACES_TOKEN}
#    ports:
#      - "1777:1777"
#      - "9411:9411"
#      - "9943:9943"
#      - "6831:6831"
#      - "6832:6832"
#      - "14250:14250"
#      - "14268:14268"
#      - "4317:4317"
#      - "5681:55681"
#      - "8888:8888"