server:
  port: 8081

spring:
  application:
    name: oauth2-server
  security:
    user:
      name: user
      password: password
    oauth2:
      authorization server:
        client:
          oidc-client:
            registration:
              client-id: "oidc-client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "client-credentials"
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://localhost:8080/login/oauth2/code/yipingx"
              scopes:
                - "openid"
                - "profile"
                - "user.read"
            require-authorization-consent: true
