
server:
  ssl:
    client-auth: none
    enabled-protocols: TLSv1.3
    enabled: false

spring:
  datasource:
    url: jdbc:h2:mem:testdb #
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: create #create update
    properties:
      hibernate:
        format_sql: false
        jdbc.batch_size: 10
        order_inserts: true
        order_updates: true
        generate_statistics: true
  cloud:
    loadbalancer:
      nacos:
        enabled: false

logging.config: classpath:log4j2.xml
