server:
  port: 8094
  ssl:
    enabled: true
    client-auth: none
    bundle: "defaultBundle"
#    key-store: "classpath:keystore/keystore.p12"
#    key-store-password: "123456"

#    bundle: "web-server-pem-e"
#    key-store: "classpath:keystore-encrypt/ca-key.pem"
#    key-store-type: pem

# https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.1.0-Configuration-Changelog
# docker run -d -p 9411:9411 openzipkin/zipkin

spring:
  application:
    name: echoServer
  cloud:
    nacos:
      discovery:
        server-addr: "localhost:8848"
        ip: localhost
        secure: true
        enabled: false
  ssl:
    bundle:
      jks: # https://spring.io/blog/2023/06/07/securing-spring-boot-applications-with-ssl
        web-server:
          keystore:
            location: "classpath:keystore/keystore.p12"
            password: "123456"
          truststore:
            location: "classpath:keystore/certstore.p12"
            password: "123456"
      pem:
        web-server-pem:
          keystore:
            certificate: "classpath:keystore2/cert.pem"
            private-key: "classpath:keystore2/cert-key.pem"
            private-key-password: 123456
        web-server-pem-e:
          keystore:
            certificate: "classpath:keystore-encrypt/cert.pem"
            private-key: "classpath:keystore-encrypt/ca-key.pem"
            private-key-password: 123456
#  datasource:
#    url: "jdbc:mysql://localhost:3306/companyproj?rewriteBatchedStatements=true" #
##    username: yipingx
##    password: Xyp54250
#    username: "matt.xia"
#    password: "matt.xia.1234"
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
#    show-sql: false
#    hibernate:
#      ddl-auto: update #create update
#    properties:
#      hibernate:
#        format_sql: false
#        jdbc.batch_size: 10
#        order_inserts: true
#        order_updates: true
#        generate_statistics: true

  datasource:
    url: jdbc:h2:mem:testdb #
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create

management:
  tracing:
    enabled: true
  endpoints:
    web:
      exposure:
        include: "*"


secret:
  keystore:
    entries:
      tcghl:
        type: vault
        url: "https://vault.tcghl.com"
#        url: "https://localhost:8180"
        ca-path: "d:/tools/vault/1.14/tcghl-com-crt.pem"
#        ca-path: "d:/tools/vault/1.14/ca.pem"
        paths:
          pathKeyStore:
#            secret-path: "/v1/kv_xyp/data/dev"
            secret-path: "/v1/secret/data/dev/paradise/keystore"
            bundles:
              defaultBundle:
                trust-store-field: "trust_store"
                trust-store-password-field: "password"
                key-store-field: "key_store"
                key-store-password-field: "password"
      aws:
        type: aws
        region: "ap-southeast-1"
        paths:
          defaultPath:
            bundles:
              awsBundle1:
                key-store-field: "key_store"
