server:
  port: 8093
  ssl:
    enabled: true
    # explicit key store so intellij can recognize https
#    key-store: "classpath:keystore/keystore.p12"
#    key-store-password: "123456"
    key-store: "classpath:keystore/keystore.pem"
#    bundle: "clientStoreJks"
    bundle: "clientStorePem"
    key-store-type: pem

my:
  name: "xypxyp"
  age: 11

name:
  a:
    b: ${nameab}

spring:
  application:
    name: callerServer
#  cloud:
#    nacos:
#      discovery:
#        server-addr: "localhost:8848"
#        enabled: false
#      config:
#        server-addr: "localhost:8848"
#        group: "xyp.nacos"
  #        import-check:
#          enabled: false
  ssl:
    bundle:
      jks:
        clientStoreJks:
          keystore:
            location: "classpath:keystore/keystore.p12"
            password: "123456"
          truststore:
            location: "classpath:keystore/certstore.p12"
            password: "123456"
        feignStore:
          truststore:
            location: "classpath:keystore/certstore.p12"
            password: "123456"
          keystore:
            location: "classpath:keystore/keystore.p12"
            password: "123456"
      pem:
        clientStorePem:
          keystore:
            certificate: "classpath:keystore/certstore.pem"
            private-key: "classpath:keystore/keystore.pem"
            private-key-password: 123456


  datasource:
    url: jdbc:mysql://localhost:3306/companyproj?rewriteBatchedStatements=true #
    #  username: matt.xia
    #  password: Q1w2e3r4
    username: yipingx
    password: Xyp54250
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: update #create update
    properties:
      hibernate:
        format_sql: false
        jdbc.batch_size: 10
        order_inserts: true
        order_updates: true
        generate_statistics: true
  web:
    resources:
      static-locations: "file:caller/src/main/resources/static"
  freemarker:
    suffix: ""
    template-loader-path: "file:caller/src/main/resources/template"
    cache: false
#  config:
#    import: "nacos:conf1"

app:
  service-principal: 111
  keytab-location: 111

springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    path: "swagger-ui-custom.html"

echo:
  url: "https://localhost:8094"

management:
  tracing:
    enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
      path-mapping:
        prometheus: ""
#  otlp:
#    metrics:
#      export:
#        enabled: true
#        url: "http://localhost:5555"
#    tracing:
#      endpoint: "http://localhost:4318"
logging:
  file:
    path: logs
