server:
  port: 8093
  ssl:
    enabled: true
    key-store: "classpath:keystore/keystore.p12"
    key-store-password: "123456"
    bundle: "clientStoreJks"
#docker run -d -p 9411:9411 openzipkin/zipkin

spring:
  application:
    name: callerServer
  cloud:
    nacos:
      discovery:
        server-addr: "localhost:8848"
        enabled: true
  ssl.bundle:
    jks:
      clientStoreJks:
        keystore:
          location: "classpath:keystore/keystore.p12"
          password: "123456"
        truststore:
          location: "classpath:keystore/certstore.p12"
          password: "123456"
      feignStore:
        truststore:
          location: "classpath:keystore/certstore.p12"
          password: "123456"
        keystore:
          location: "classpath:keystore/keystore.p12"
          password: "123456"
  datasource:
    url: jdbc:mysql://localhost:3306/companyproj?rewriteBatchedStatements=true #
    #  username: matt.xia
    #  password: Q1w2e3r4
    username: yipingx
    password: Xyp54250
    driver-class-name: com.mysql.cj.jdbc.Driver
# No need to provide a trust store if server doesn't accept client ssl authentication.
# But need trust store if ssl call to another server

#management:
#  tracing.sampling.probability: 1.0
#  endpoints.web.exposure.include: prometheus

logging.config: classpath:log4j2.xml

app:
  service-principal: 111
  keytab-location: 111

springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    path: "swagger-ui-custom.html"

echo:
  url: "https://localhost:8094"

# if not provide below, still work:
#spring.cloud.loadbalancer.nacos.enabled: true

management:
  tracing:
    enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
