
server:
  ssl:
    enabled: true

spring:
  datasource:
    url: jdbc:h2:mem:testdb #
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  cloud:
    openfeign:
      client:
        config:
          echoServer:
            url: "http://localhost:8094"



secret:
  keystore:
    entries:
      tcghl:
        type: vault
        url: "https://vault.tcghl.com"
        #        url: "https://localhost:8180"
        ca-path: "d:/tools/vault/1.14/tcghl-com-crt.pem"
        #        ca-path: "d:/tools/vault/1.14/ca.pem"
        paths:
          pathKeyStore:
            #            secret-path: "/v1/kv_xyp/data/dev"
            secret-path: "/v1/secret/data/dev/paradise/keystore"
            bundles:
              defaultBundle2:
                trust-store-field: "trust_store"
                trust-store-password-field: "password"
                key-store-field: "key_store"
                key-store-password-field: "password"