management:
  otlp:
    metrics:
      export:
        enabled: true
        url: "http://localhost:6666/v1/metrics"
        step: 10s
  # this is for actuator web, premeditates doesn't read actuator if using otel
  # this is only for debug purpose because you can verify metrics on web
  endpoints:
    web:
      exposure:
        include: health,metrics
