management:
  otlp:
    metrics:
      export:
        enabled: true
#        url: "http://localhost:6666/v1/metrics"
        url: "http://192.168.56.101:6666/v1/metrics"
        step: 10s
    tracing:
#      endpoint: "http://localhost:6666/v1/traces"
      endpoint: "http://192.168.56.101:6666/v1/traces"
  # this is only for actuator web, prometheus doesn't read actuator if using otel
  # this is only for debug purpose because you can verify metrics on web
  endpoints:
    web:
      exposure:
        include: health,metrics

  # add tag in metrics so that we can use in prometheus
  metrics:
    tags:
      app-name: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
