

# https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.1.0-Configuration-Changelog
server.port: 8094
#docker run -d -p 9411:9411 openzipkin/zipkin

management:
  tracing.sampling.probability: 1.0
  endpoints.web.exposure.include: "*"

# https://spring.io/blog/2023/06/07/securing-spring-boot-applications-with-ssl
spring.ssl.bundle:
  jks:
    web-server:
      keystore:
        location: "classpath:keystore/keystore.p12"
        password: "123456"
#      truststore:
#        location: "classpath:keystore/certstore.p12"
#        password: "123456"


server:
  ssl:
    enabled: false
    bundle: "web-server"
    client-auth: NONE

spring.datasource:
  url: jdbc:mysql://localhost:3306/companyproj?rewriteBatchedStatements=true #
#  username: matt.xia
#  password: Q1w2e3r4
  username: yipingx
  password: Xyp54250
  driver-class-name: com.mysql.cj.jdbc.Driver

spring.jpa:
  database-platform: org.hibernate.dialect.MySQLDialect
  show-sql: false
  hibernate:
    ddl-auto: update #create update
  properties:
    hibernate:
      format_sql: false
      jdbc.batch_size: 10
      order_inserts: true
      order_updates: true
      generate_statistics: true

logging.config: classpath:log4j2.xml

spring:
  cloud:
    nacos:
      discovery:
        server-addr: "172.19.83.237:8848/"
  application:
    name: echoServer