spring:
  cloud:
    consul:
      enabled: false
      discovery:
        enabled: false
    vault:
      enabled: false
      discovery:
        enabled: false

com:
  tcg:
    paradise:
      common:
        service:
          document:
            client:
#               host-port: "localhost:8086"
              host-port: "10.225.4.63:8086"